// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Company              string   `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_8f99814a48d336ca, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_8f99814a48d336ca, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Token                *Token   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_8f99814a48d336ca, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Response) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_8f99814a48d336ca, []int{3}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_8f99814a48d336ca, []int{4}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*Request)(nil), "auth.Request")
	proto.RegisterType((*Response)(nil), "auth.Response")
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*Error)(nil), "auth.Error")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_8f99814a48d336ca) }

var fileDescriptor_auth_8f99814a48d336ca = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4f, 0xe3, 0x30,
	0x10, 0xdd, 0x34, 0x1f, 0x6d, 0xa7, 0x6a, 0x0f, 0xa3, 0x3d, 0x44, 0x3d, 0xac, 0xda, 0xac, 0xb4,
	0x5a, 0x84, 0xd4, 0x43, 0x39, 0x73, 0xa8, 0x10, 0xe2, 0x1e, 0x01, 0xe2, 0x6a, 0x9a, 0x91, 0x88,
	0x48, 0xe3, 0x60, 0xbb, 0x20, 0xfe, 0x03, 0x47, 0x7e, 0x17, 0xbf, 0x09, 0x7b, 0x9c, 0x40, 0x54,
	0x21, 0xc1, 0x29, 0xf3, 0xde, 0x3c, 0xdb, 0x6f, 0xde, 0x04, 0x40, 0xec, 0xcd, 0xdd, 0xaa, 0x51,
	0xd2, 0x48, 0x8c, 0x5c, 0x9d, 0xbd, 0x04, 0x10, 0x5d, 0x69, 0x52, 0x38, 0x83, 0x41, 0x59, 0xa4,
	0xc1, 0x22, 0xf8, 0x3f, 0xce, 0x6d, 0x85, 0x08, 0x51, 0x2d, 0x76, 0x94, 0x0e, 0x98, 0xe1, 0x1a,
	0x53, 0x18, 0x6e, 0xe5, 0xae, 0x11, 0xf5, 0x73, 0x1a, 0x32, 0xdd, 0x41, 0xfc, 0x0d, 0x31, 0xed,
	0x44, 0x59, 0xa5, 0x11, 0xf3, 0x1e, 0xe0, 0x1c, 0x46, 0x8d, 0xd0, 0xfa, 0x49, 0xaa, 0x22, 0x8d,
	0xb9, 0xf1, 0x81, 0xdd, 0x09, 0x23, 0xef, 0xa9, 0x4e, 0x13, 0x7f, 0x82, 0x41, 0x36, 0x86, 0x61,
	0x4e, 0x0f, 0x7b, 0xd2, 0x26, 0x7b, 0x0d, 0x60, 0x94, 0x93, 0x6e, 0x64, 0xad, 0x09, 0xff, 0x40,
	0xb4, 0xb7, 0x2e, 0xd9, 0xdf, 0x64, 0x0d, 0x2b, 0x9e, 0xc3, 0xf9, 0xce, 0x99, 0xc7, 0x05, 0xc4,
	0xee, 0xab, 0xad, 0xdd, 0xf0, 0x40, 0xe0, 0x1b, 0xf8, 0x17, 0x12, 0x52, 0x4a, 0x5a, 0x49, 0xc8,
	0x92, 0x89, 0x97, 0x9c, 0x3b, 0x2e, 0x6f, 0x5b, 0xb8, 0xec, 0x4c, 0x45, 0xfc, 0x4e, 0xab, 0xb9,
	0x74, 0x54, 0xe7, 0xf0, 0x06, 0x62, 0xc6, 0x9f, 0x03, 0x04, 0xbd, 0x01, 0x1c, 0xfb, 0x28, 0x2a,
	0x9b, 0xa4, 0xcb, 0x6d, 0x94, 0x7b, 0xf0, 0xa3, 0xc7, 0xb3, 0x53, 0x88, 0x99, 0x70, 0xd1, 0x6f,
	0x65, 0x41, 0x7c, 0x71, 0x9c, 0x73, 0x6d, 0x07, 0x9c, 0x14, 0xa4, 0xb7, 0xaa, 0x6c, 0x4c, 0x29,
	0xeb, 0x76, 0x2b, 0x7d, 0x6a, 0xfd, 0x66, 0x37, 0xb9, 0xb1, 0xb7, 0xe2, 0x3f, 0x48, 0xce, 0x14,
	0x09, 0x43, 0xd8, 0x8b, 0x61, 0x3e, 0xf3, 0x75, 0x97, 0x68, 0xf6, 0xcb, 0x9a, 0x0a, 0x2f, 0xc8,
	0x7c, 0x23, 0x3a, 0x82, 0xc4, 0x8a, 0x36, 0x55, 0x85, 0xd3, 0xae, 0xc7, 0xeb, 0xf9, 0x42, 0xba,
	0x6c, 0xdf, 0xef, 0x5f, 0xd8, 0x4f, 0xd0, 0x4a, 0x8e, 0x61, 0x7a, 0xed, 0x02, 0xb1, 0xe6, 0x7c,
	0x88, 0xfd, 0xfe, 0x81, 0xf8, 0x36, 0xe1, 0xff, 0xf4, 0xe4, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x5b,
	0x34, 0x92, 0x47, 0xb5, 0x02, 0x00, 0x00,
}
